### ISSUE TITLE
a `--all-regions` option that just scans all avaliable regions for the given worlds

### ISSUE THREAD

**Issue by walksanatora** [RundownRhino/RegionScanner#12]
since I have to generate a large area. Rather than trying to find all the regions I filled and the box surrounding them. I wish for a option to just add "select all" regions (would also have it skip regions in the box that don't exists. perhaps being faster the if I were to define a box)

**Comment by RundownRhino** [comment]
The reason I did the zone thing is because users might want to only scan regions they know are fully generated (e.g. only the zone they've pregenerated via Chunk Pregenerator). My understanding is that some chunks in the world may have a [status other than minecraft:full](https://minecraft.wiki/w/Chunk_format), meaning they are only partially generated. Including them into the scan might pollute the results.
Though I haven't actually tested whether this is the case (maybe fastanvil filters them by default and I didn't notice), and should probably try and get such a polluted result to justify this.

**Comment by RundownRhino** [comment]
Looks like, indeed, if you just pop into a dimension, *most* of the chunks in the generated area will be protochunks. The statistics for them are way different.

What I'm worried about, though, is whether mods obey the whole `minecraft:full` thing. It might be possible for some mods to stealthily do generation on chunks *after* they are supposed to have been generated fully, and if that's the case, including all full chunks will miss out on some of the generation.

**Comment by RundownRhino** [comment]
I've implemented skipping of protochunks, which allowed me to also implement scanning all regions without *too* much fear.

**Comment by RundownRhino** [comment]
I'm a bit concerned about scanning all dimensions because some dimensions are... weird. Woot has a dimension meant entirely to summon and kill virtual mobs in, say. Though on the other hand, that probably means it's not a big deal to scan them, they'll just be empty?..
I guess what I could do eventually is add an interactive mode where you can select all the dimensions you want to scan via a nice [inquire](<https://github.com/mikaelmello/inquire>) prompt. That'd be faster than listing them all.
